# Generated by Django 3.2.3 on 2021-05-31 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_accident', models.CharField(max_length=255, verbose_name='Numero')),
                ('date_accident', models.DateField(verbose_name='Date')),
                ('heure_accident', models.TimeField(verbose_name='Heure')),
                ('lieu_accident', models.CharField(max_length=255, verbose_name='Lieu')),
                ('mesures_prises', models.TextField(blank=True, null=True, verbose_name='Mesures Prises')),
                ('circonstances', models.TextField(blank=True, null=True, verbose_name='Circonstances')),
                ('infractions_relevees', models.TextField(verbose_name='Infractions Relevees')),
                ('derniere_mesures_prises', models.TextField(verbose_name='Derniere Mesures Prises')),
                ('autres_dommages', models.TextField(blank=True, null=True, verbose_name="Autres dommages causes par l'accident")),
                ('assiste_de', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('etabli_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_etablie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255, verbose_name='Nom & Prenom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=255, verbose_name='Lieu de naissance')),
                ('filiation', models.CharField(max_length=255, verbose_name='Filiation')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('domicile', models.CharField(max_length=255, verbose_name='Domicile')),
                ('telephone', models.CharField(max_length=15, verbose_name='Telephone')),
                ('comportement', models.CharField(max_length=200, verbose_name='Comportement')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=200, verbose_name='Numero')),
                ('genre', models.CharField(max_length=255, verbose_name='Genre')),
                ('marque', models.CharField(max_length=255, verbose_name='Marque')),
                ('puissance', models.CharField(max_length=255, verbose_name='Puissance')),
                ('charge_total', models.CharField(max_length=255, verbose_name='Charge Total')),
                ('dimension', models.CharField(max_length=255, verbose_name='Dimension')),
                ('date_mise_circulation', models.DateField(verbose_name='Date de mise en circulation')),
                ('derniere_visite_technique', models.DateField(verbose_name='Derniere visite technique')),
                ('kilometrage', models.CharField(max_length=255, verbose_name='Kilometrage')),
                ('etat_general', models.TextField(verbose_name='Etat general')),
                ('valeur_systeme_freinage', models.CharField(max_length=255, verbose_name='Valeur du systeme de freinage')),
                ('etat_pneus_avant', models.TextField(verbose_name='Etat des pneus avant')),
                ('etat_pneus_arriere', models.TextField(verbose_name='Etat des pneus arriere')),
                ('etat_parebrise', models.TextField(verbose_name='Etat du parebrise')),
                ('position_levier_vitesse', models.TextField(verbose_name='Position du levier de changement de vitesse')),
                ('presence_poste_radio', models.BooleanField(default=True, verbose_name="Presence d'un poste radio")),
                ('degats_materiels', models.TextField(verbose_name='Degats materiels')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.accident')),
            ],
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Victime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255, verbose_name='Nom & Prenom')),
                ('filiation_complete', models.CharField(max_length=255, verbose_name='Filiation complete')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('nature_des_blessures', models.TextField(verbose_name='Nature des blessures')),
                ('position_moment_accident', models.CharField(max_length=255, verbose_name="Position au moment de l'accident")),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.accident')),
            ],
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255, verbose_name='Nom & Prenom')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('position_moment_accident', models.CharField(max_length=255, verbose_name="Position au moment de l'accident")),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.accident')),
            ],
        ),
        migrations.CreateModel(
            name='Retroviseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existance', models.BooleanField(default=True, verbose_name='Existance')),
                ('fonctionel', models.BooleanField(default=True, verbose_name='Fonctionel')),
                ('position', models.BooleanField(default=True, verbose_name='Position')),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255, verbose_name='Nom & Prenom')),
                ('domicile', models.CharField(max_length=255, verbose_name='Domicile')),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Permis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=200, verbose_name='Numero')),
                ('delivre_par', models.CharField(max_length=200, verbose_name='Delivre par')),
                ('delivre_le', models.DateField(verbose_name='Delivre le')),
                ('lieu', models.CharField(max_length=255, verbose_name='Lieu')),
                ('conducteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.conducteur')),
            ],
        ),
        migrations.CreateModel(
            name='IndicateurVitesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existance', models.BooleanField(default=True, verbose_name='Existance')),
                ('fonctionel', models.BooleanField(default=True, verbose_name='Fonctionel')),
                ('position', models.BooleanField(default=True, verbose_name='Position')),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='IndicateurDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existance', models.BooleanField(default=True, verbose_name='Existance')),
                ('fonctionel', models.BooleanField(default=True, verbose_name='Fonctionel')),
                ('position', models.BooleanField(default=True, verbose_name='Position')),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibilite', models.CharField(max_length=255, verbose_name='Visibilite')),
                ('chaussee', models.CharField(max_length=255, verbose_name='Chausse')),
                ('largeur', models.CharField(max_length=255, verbose_name='Largeur')),
                ('eclairage', models.CharField(max_length=255, verbose_name='Eclairage')),
                ('tracesFreinage', models.CharField(max_length=255, verbose_name='Traces de freinage')),
                ('tracesSang', models.CharField(max_length=255, verbose_name='Traces de sang')),
                ('tracePneu', models.CharField(max_length=255, verbose_name='Traces de pneus')),
                ('PassagePieton', models.CharField(max_length=255, verbose_name='Passage pieton')),
                ('condition_atmospherique', models.TextField(verbose_name='Conditions atmospheriques')),
                ('accident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.accident')),
            ],
        ),
        migrations.CreateModel(
            name='EssuieGlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existance', models.BooleanField(default=True, verbose_name='Existance')),
                ('fonctionel', models.BooleanField(default=True, verbose_name='Fonctionel')),
                ('position', models.BooleanField(default=True, verbose_name='Position')),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Eclairage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existance', models.BooleanField(default=True, verbose_name='Existance')),
                ('fonctionel', models.BooleanField(default=True, verbose_name='Fonctionel')),
                ('position', models.BooleanField(default=True, verbose_name='Position')),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration', models.TextField(verbose_name='Declaration')),
                ('infraction', models.TextField(blank=True, null=True, verbose_name='Infraction')),
                ('conducteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.conducteur')),
            ],
        ),
        migrations.AddField(
            model_name='conducteur',
            name='vehicule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.vehicule'),
        ),
        migrations.CreateModel(
            name='Avertisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existance', models.BooleanField(default=True, verbose_name='Existance')),
                ('fonctionel', models.BooleanField(default=True, verbose_name='Fonctionel')),
                ('position', models.BooleanField(default=True, verbose_name='Position')),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('numero_police', models.CharField(max_length=200, verbose_name='Numero police')),
                ('date_debut', models.DateField(verbose_name='Date debut')),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accident.vehicule')),
            ],
        ),
        migrations.AddField(
            model_name='accident',
            name='type_accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.typeaccident'),
        ),
    ]
