# Generated by Django 3.2.3 on 2021-06-01 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='date_accident',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='heure_accident',
        ),
    ]
