# Generated by Django 3.2.3 on 2021-06-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0003_auto_20210601_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='charge_total',
            field=models.CharField(blank=True, max_length=255, verbose_name='Charge Total'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='degats_materiels',
            field=models.TextField(blank=True, verbose_name='Degats materiels'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='dimension',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dimension'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='etat_general',
            field=models.TextField(blank=True, verbose_name='Etat general'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='etat_parebrise',
            field=models.TextField(blank=True, verbose_name='Etat du parebrise'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='etat_pneus_arriere',
            field=models.TextField(blank=True, verbose_name='Etat des pneus arriere'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='etat_pneus_avant',
            field=models.TextField(blank=True, verbose_name='Etat des pneus avant'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='kilometrage',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kilometrage'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='position_levier_vitesse',
            field=models.TextField(blank=True, verbose_name='Position du levier de changement de vitesse'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='presence_poste_radio',
            field=models.BooleanField(blank=True, default=True, verbose_name="Presence d'un poste radio"),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='valeur_systeme_freinage',
            field=models.CharField(blank=True, max_length=255, verbose_name='Valeur du systeme de freinage'),
        ),
    ]
