# Generated by Django 3.2.3 on 2021-06-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0004_auto_20210604_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='puissance',
            field=models.CharField(blank=True, max_length=255, verbose_name='Puissance'),
        ),
    ]
