# Generated by Django 3.2.3 on 2021-06-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0005_alter_vehicule_puissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='comportement',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comportement'),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='date_naissance',
            field=models.DateField(blank=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='domicile',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domicile'),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='filiation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Filiation'),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telephone'),
        ),
    ]
