# Generated by Django 3.2.3 on 2021-06-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0006_auto_20210605_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='derniere_mesures_prises',
            field=models.TextField(blank=True, null=True, verbose_name='Derniere Mesures Prises'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='infractions_relevees',
            field=models.TextField(blank=True, null=True, verbose_name='Infractions Relevees'),
        ),
    ]
