# Generated by Django 3.2.3 on 2021-06-07 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0008_alter_conducteur_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='type_accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accident.typeaccident'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accident.accident'),
        ),
    ]
