# Generated by Django 3.2.3 on 2021-06-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0011_audition_cloture_conduite_confrontation_interrogatoire_mission_notification_pv_requisition_saisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloture',
            name='pv_ptr',
        ),
        migrations.RemoveField(
            model_name='conduite',
            name='pv_ptr',
        ),
        migrations.RemoveField(
            model_name='confrontation',
            name='pv_ptr',
        ),
        migrations.RemoveField(
            model_name='interrogatoire',
            name='pv_ptr',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='pv_ptr',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='pv_ptr',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='pv_ptr',
        ),
        migrations.RemoveField(
            model_name='saisine',
            name='pv_ptr',
        ),
        migrations.DeleteModel(
            name='Audition',
        ),
        migrations.DeleteModel(
            name='Cloture',
        ),
        migrations.DeleteModel(
            name='Conduite',
        ),
        migrations.DeleteModel(
            name='Confrontation',
        ),
        migrations.DeleteModel(
            name='Interrogatoire',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PV',
        ),
        migrations.DeleteModel(
            name='Requisition',
        ),
        migrations.DeleteModel(
            name='Saisine',
        ),
    ]
