# Generated by Django 3.2.3 on 2021-06-16 13:12

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0012_auto_20210616_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPv', models.IntegerField()),
                ('objet', models.CharField(max_length=300)),
                ('description', django_summernote.fields.SummernoteTextField(blank=True, null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('affaire', models.CharField(blank=True, max_length=200, null=True)),
                ('incrimination', models.CharField(blank=True, max_length=100, null=True)),
                ('vuEtTransmis', models.BooleanField(blank=True, default=False, null=True, verbose_name='Vu et Transmis')),
                ('ouvertureEnquete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ouverture Enquete')),
                ('deroulementEtNotification', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deroulement et Transmission')),
                ('controleEtTransmission', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle et transmission')),
                ('mentionRestitution', models.BooleanField(blank=True, default=False, null=True, verbose_name='Mention et Restition')),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
