# Generated by Django 3.2.3 on 2021-06-15 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Matricule')),
                ('telephone', models.CharField(max_length=15, unique=True, verbose_name='Telephone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('grade', models.CharField(blank=True, max_length=255, verbose_name='Grade')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.departement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
