# Generated by Django 3.2.3 on 2021-06-12 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Chef de poste', '0'), ('Secretaire', '1'), ('Chauffeur', '2'), ('Police de secours', '3')], max_length=100, verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('chauffeur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_chauffeur', to='postepolice.agentposte')),
                ('chef_de_poste', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_chef_de_poste', to='postepolice.agentposte')),
                ('police_secours', models.ManyToManyField(to='postepolice.AgentPoste')),
                ('secretaire', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_secretaire', to='postepolice.agentposte')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectConsigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('numero_mention', models.IntegerField(blank=True, null=True, verbose_name='Numero mention')),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('nom_prenom', models.CharField(max_length=200, verbose_name='Nom et Prenom')),
                ('adresse', models.CharField(max_length=200, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=15, unique=True, verbose_name='telephone')),
                ('code_postal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ville')),
                ('objet', models.TextField(verbose_name='Objet')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postepolice.brigade')),
            ],
        ),
        migrations.CreateModel(
            name='Perte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('numero_mention', models.IntegerField(blank=True, null=True, verbose_name='Numero mention')),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('nom_prenom', models.CharField(max_length=200, verbose_name='Nom et Prenom')),
                ('adresse', models.CharField(max_length=200, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=15, unique=True, verbose_name='telephone')),
                ('code_postal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ville')),
                ('objet', models.TextField(verbose_name='Objet')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postepolice.brigade')),
            ],
        ),
        migrations.CreateModel(
            name='MainCourante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('numero_mention', models.IntegerField(blank=True, null=True, verbose_name='Numero mention')),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postepolice.brigade')),
            ],
        ),
        migrations.CreateModel(
            name='Ecrou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('numero_mention', models.IntegerField(blank=True, null=True, verbose_name='Numero mention')),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('nom_prenom', models.CharField(max_length=200, verbose_name='Nom et Prenom')),
                ('adresse', models.CharField(max_length=200, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=15, unique=True, verbose_name='telephone')),
                ('code_postal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ville')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postepolice.brigade')),
                ('objects_consignes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postepolice.objectconsigne')),
            ],
        ),
    ]
