# Generated by Django 3.2.3 on 2021-06-13 04:55

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainte',
            name='contenu',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Contenu'),
        ),
    ]
