# Generated by Django 3.2.3 on 2021-06-13 04:58

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0002_alter_plainte_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perte',
            name='contenu',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Contenu'),
        ),
    ]
