# Generated by Django 3.2.3 on 2021-06-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0003_alter_perte_contenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecrou',
            name='brigade',
        ),
        migrations.RemoveField(
            model_name='ecrou',
            name='date',
        ),
        migrations.RemoveField(
            model_name='maincourante',
            name='brigade',
        ),
        migrations.RemoveField(
            model_name='maincourante',
            name='date',
        ),
        migrations.RemoveField(
            model_name='perte',
            name='brigade',
        ),
        migrations.RemoveField(
            model_name='perte',
            name='date',
        ),
        migrations.RemoveField(
            model_name='plainte',
            name='brigade',
        ),
        migrations.RemoveField(
            model_name='plainte',
            name='date',
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postepolice.brigade')),
            ],
        ),
        migrations.AddField(
            model_name='ecrou',
            name='registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postepolice.registre'),
        ),
        migrations.AddField(
            model_name='maincourante',
            name='registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postepolice.registre'),
        ),
        migrations.AddField(
            model_name='perte',
            name='registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postepolice.registre'),
        ),
        migrations.AddField(
            model_name='plainte',
            name='registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postepolice.registre'),
        ),
    ]
