# Generated by Django 3.2.3 on 2021-06-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0004_auto_20210620_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='registre',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom'),
        ),
    ]
