# Generated by Django 3.2.3 on 2021-08-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0005_registre_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecrou',
            name='objects_consignes',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Objet consigné'),
        ),
    ]
