# Generated by Django 3.2.3 on 2021-08-01 21:44

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0006_alter_ecrou_objects_consignes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plainte',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='plainte',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='plainte',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='plainte',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='plainte',
            name='ville',
        ),
        migrations.AlterField(
            model_name='plainte',
            name='objet',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Contenu'),
        ),
    ]
