# Generated by Django 3.2.3 on 2021-08-01 21:56

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0008_auto_20210801_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincourante',
            name='motif',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Motif'),
        ),
    ]
