# Generated by Django 3.2.3 on 2021-08-02 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0010_auto_20210801_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecrou',
            name='motif_garde_vue',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Motif garde à vue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecrou',
            name='suite',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Suite'),
            preserve_default=False,
        ),
    ]
