# Generated by Django 3.2.3 on 2021-08-02 18:13

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0011_auto_20210802_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='photo1',
            field=models.ImageField(default=django.utils.timezone.now, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plainte',
            name='photo2',
            field=models.ImageField(default=django.utils.timezone.now, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GardeAVue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postepolice.registre')),
            ],
        ),
    ]
