# Generated by Django 3.2.3 on 2021-08-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0013_auto_20210802_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardeavue',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='N°'),
        ),
    ]
