# Generated by Django 3.2.3 on 2021-08-02 20:31

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0014_gardeavue_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardeavue',
            name='aupres_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Auprès de'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='date_conduite',
            field=models.DateField(blank=True, null=True, verbose_name='Date conduite'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de debut'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='date_prolongation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la prolongation de la garde à vue'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='date_pv',
            field=models.DateField(blank=True, null=True, verbose_name='Date PV'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='decision_magistrat',
            field=models.CharField(blank=True, choices=[('AC', 'Accorée'), ('RE', 'Refusé')], default='AC', max_length=255, null=True, verbose_name='Décision du magistrat'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='devant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Devant'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='domicile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicile'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='duree_audition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Durée audition'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='duree_repos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Durée repos'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='heure_conduite',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure conduite'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='heure_debut_audition',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de debut audition'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='heure_debut_repos',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de debut repos'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='heure_fin_audition',
            field=models.TimeField(blank=True, null=True, verbose_name='heure de fin audition'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='heure_fin_repos',
            field=models.TimeField(blank=True, null=True, verbose_name='heure de fin repos'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='heure_prolongation',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de la prolongation de la garde à vue'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='liberte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Liberté'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='motif',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True, verbose_name='Motif de la garde à vue'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='numero_pv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='P.V.n°'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='observations',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='prise_par',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prise par'),
        ),
        migrations.AlterField(
            model_name='gardeavue',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession'),
        ),
    ]
