# Generated by Django 3.2.3 on 2021-08-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0015_auto_20210802_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardeavue',
            name='motif',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de la garde à vue'),
        ),
    ]
