# Generated by Django 3.2.3 on 2021-08-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postepolice', '0016_alter_gardeavue_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainte',
            name='photo1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='photo2',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
