# Generated by Django 3.2.3 on 2021-08-05 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postepolice', '0017_auto_20210803_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='affecte',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'police judiciaire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Affectée à'),
        ),
    ]
