# Generated by Django 3.2.3 on 2021-05-18 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPv', models.IntegerField()),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audition',
            fields=[
                ('pv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policejudiciaire.pv')),
                ('affaire', models.CharField(max_length=200)),
                ('incrimination', models.CharField(max_length=100)),
            ],
            bases=('policejudiciaire.pv',),
        ),
        migrations.CreateModel(
            name='Cloture',
            fields=[
                ('pv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policejudiciaire.pv')),
                ('affaire', models.CharField(max_length=200)),
                ('incrimination', models.CharField(max_length=100)),
                ('deroulementEtNotification', models.BooleanField(verbose_name=True)),
                ('controleEtTransmission', models.BooleanField(verbose_name=True)),
                ('mentionRestitution', models.BooleanField(verbose_name=True)),
            ],
            bases=('policejudiciaire.pv',),
        ),
        migrations.CreateModel(
            name='Conduite',
            fields=[
                ('pv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policejudiciaire.pv')),
                ('affaire', models.CharField(max_length=200)),
                ('incrimination', models.CharField(max_length=100)),
            ],
            bases=('policejudiciaire.pv',),
        ),
        migrations.CreateModel(
            name='Confrotation',
            fields=[
                ('pv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policejudiciaire.pv')),
                ('affaire', models.CharField(max_length=200)),
                ('incrimination', models.CharField(max_length=100)),
            ],
            bases=('policejudiciaire.pv',),
        ),
        migrations.CreateModel(
            name='GardeAVue',
            fields=[
                ('pv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policejudiciaire.pv')),
                ('affaire', models.CharField(max_length=200)),
                ('incrimination', models.CharField(max_length=100)),
            ],
            bases=('policejudiciaire.pv',),
        ),
        migrations.CreateModel(
            name='Interrogatoire',
            fields=[
                ('pv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policejudiciaire.pv')),
                ('affaire', models.CharField(max_length=200)),
                ('incrimination', models.CharField(max_length=100)),
            ],
            bases=('policejudiciaire.pv',),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('pv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policejudiciaire.pv')),
                ('affaire', models.CharField(max_length=200)),
                ('incrimination', models.CharField(max_length=100)),
            ],
            bases=('policejudiciaire.pv',),
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('pv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policejudiciaire.pv')),
                ('reference', models.CharField(max_length=200)),
            ],
            bases=('policejudiciaire.pv',),
        ),
        migrations.CreateModel(
            name='Saisine',
            fields=[
                ('pv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policejudiciaire.pv')),
                ('affaire', models.CharField(max_length=200)),
                ('incrimination', models.CharField(max_length=100)),
                ('vuEtTransmis', models.BooleanField(verbose_name=True)),
                ('ouvertureEnquete', models.BooleanField(verbose_name=True)),
            ],
            bases=('policejudiciaire.pv',),
        ),
    ]
