# Generated by Django 3.2.3 on 2021-05-18 12:48


from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ('policejudiciaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv',
            name='description',
            field=TextField(blank=True, null=True),
        ),
    ]
