# Generated by Django 3.2.3 on 2021-05-19 05:57

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policejudiciaire', '0002_alter_pv_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
