# Generated by Django 3.2.3 on 2021-05-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policejudiciaire', '0003_alter_pv_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confrotation',
            new_name='Confrontation',
        ),
    ]
