# Generated by Django 3.2.3 on 2021-05-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policejudiciaire', '0004_rename_confrotation_confrontation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv',
            name='objet',
            field=models.CharField(max_length=300),
        ),
    ]
