# Generated by Django 3.2.3 on 2021-05-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policejudiciaire', '0005_alter_pv_objet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GardeAVue',
            new_name='Notification',
        ),
    ]
