# Generated by Django 3.2.3 on 2021-05-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policejudiciaire', '0006_rename_gardeavue_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saisine',
            name='ouvertureEnquete',
            field=models.BooleanField(default=True, verbose_name='Ouverture Enquete'),
        ),
        migrations.AlterField(
            model_name='saisine',
            name='vuEtTransmis',
            field=models.BooleanField(default=True, verbose_name='Vu et Transmis'),
        ),
    ]
