# Generated by Django 3.2.3 on 2021-08-04 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pojudiciaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
