# Generated by Django 3.2.3 on 2021-08-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojudiciaire', '0004_alter_crime_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='user',
        ),
    ]
